
version: 2

models:
  - name: FCT_ORDERS
    description: "A starter dbt model"
    columns:
      - name: order_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
